// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: auth_identity.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getUserPasswordHash = `-- name: GetUserPasswordHash :one
SELECT identity_id, user_id, provider, provider_subject, provider_hash, created_at, updated_at FROM auth_identity WHERE user_id = $1
`

func (q *Queries) GetUserPasswordHash(ctx context.Context, userID uuid.UUID) (AuthIdentity, error) {
	row := q.db.QueryRowContext(ctx, getUserPasswordHash, userID)
	var i AuthIdentity
	err := row.Scan(
		&i.IdentityID,
		&i.UserID,
		&i.Provider,
		&i.ProviderSubject,
		&i.ProviderHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setPasswordForUser = `-- name: SetPasswordForUser :one
INSERT INTO auth_identity (user_id, provider, provider_subject, provider_hash)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING identity_id, user_id, provider, provider_subject, provider_hash, created_at, updated_at
`

type SetPasswordForUserParams struct {
	UserID          uuid.UUID
	Provider        string
	ProviderSubject sql.NullString
	ProviderHash    sql.NullString
}

func (q *Queries) SetPasswordForUser(ctx context.Context, arg SetPasswordForUserParams) (AuthIdentity, error) {
	row := q.db.QueryRowContext(ctx, setPasswordForUser,
		arg.UserID,
		arg.Provider,
		arg.ProviderSubject,
		arg.ProviderHash,
	)
	var i AuthIdentity
	err := row.Scan(
		&i.IdentityID,
		&i.UserID,
		&i.Provider,
		&i.ProviderSubject,
		&i.ProviderHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
