// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: booking.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const confirmBooking = `-- name: ConfirmBooking :one
UPDATE booking SET status='confirmed',
    updated_at = NOW()
WHERE booking_id = $1
RETURNING booking_id, organization_id, requested_by_user_id, property_id, preferred_date, schedule_start, schedule_end, status, created_at, updated_at, cancelled_at
`

func (q *Queries) ConfirmBooking(ctx context.Context, bookingID uuid.UUID) (Booking, error) {
	row := q.db.QueryRowContext(ctx, confirmBooking, bookingID)
	var i Booking
	err := row.Scan(
		&i.BookingID,
		&i.OrganizationID,
		&i.RequestedByUserID,
		&i.PropertyID,
		&i.PreferredDate,
		&i.ScheduleStart,
		&i.ScheduleEnd,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const createBooking = `-- name: CreateBooking :one
INSERT INTO booking (organization_id, requested_by_user_id, property_id, preferred_date, schedule_start, schedule_end, status)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
) RETURNING booking_id, organization_id, requested_by_user_id, property_id, preferred_date, schedule_start, schedule_end, status, created_at, updated_at, cancelled_at
`

type CreateBookingParams struct {
	OrganizationID    uuid.UUID
	RequestedByUserID uuid.UUID
	PropertyID        uuid.UUID
	PreferredDate     time.Time
	ScheduleStart     time.Time
	ScheduleEnd       time.Time
	Status            string
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRowContext(ctx, createBooking,
		arg.OrganizationID,
		arg.RequestedByUserID,
		arg.PropertyID,
		arg.PreferredDate,
		arg.ScheduleStart,
		arg.ScheduleEnd,
		arg.Status,
	)
	var i Booking
	err := row.Scan(
		&i.BookingID,
		&i.OrganizationID,
		&i.RequestedByUserID,
		&i.PropertyID,
		&i.PreferredDate,
		&i.ScheduleStart,
		&i.ScheduleEnd,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const getBooking = `-- name: GetBooking :one
SELECT booking_id, organization_id, requested_by_user_id, property_id, preferred_date, schedule_start, schedule_end, status, created_at, updated_at, cancelled_at FROM booking WHERE booking_id = $1
`

func (q *Queries) GetBooking(ctx context.Context, bookingID uuid.UUID) (Booking, error) {
	row := q.db.QueryRowContext(ctx, getBooking, bookingID)
	var i Booking
	err := row.Scan(
		&i.BookingID,
		&i.OrganizationID,
		&i.RequestedByUserID,
		&i.PropertyID,
		&i.PreferredDate,
		&i.ScheduleStart,
		&i.ScheduleEnd,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
	)
	return i, err
}
