// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: booking_item.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createBookingItem = `-- name: CreateBookingItem :one
INSERT INTO booking_item(booking_id, service_id, quantity, unit_price_cents, points_award)
VALUES(
    $1,
    $2,
    $3,
    $4,
    $5
)RETURNING booking_item_id, booking_id, service_id, quantity, unit_price_cents, points_award, created_at
`

type CreateBookingItemParams struct {
	BookingID      uuid.UUID
	ServiceID      uuid.UUID
	Quantity       int32
	UnitPriceCents int32
	PointsAward    int32
}

func (q *Queries) CreateBookingItem(ctx context.Context, arg CreateBookingItemParams) (BookingItem, error) {
	row := q.db.QueryRowContext(ctx, createBookingItem,
		arg.BookingID,
		arg.ServiceID,
		arg.Quantity,
		arg.UnitPriceCents,
		arg.PointsAward,
	)
	var i BookingItem
	err := row.Scan(
		&i.BookingItemID,
		&i.BookingID,
		&i.ServiceID,
		&i.Quantity,
		&i.UnitPriceCents,
		&i.PointsAward,
		&i.CreatedAt,
	)
	return i, err
}

const getBookingItems = `-- name: GetBookingItems :many
SELECT booking_item_id, booking_id, service_id, quantity, unit_price_cents, points_award, created_at FROM booking_item WHERE booking_id=$1
`

func (q *Queries) GetBookingItems(ctx context.Context, bookingID uuid.UUID) ([]BookingItem, error) {
	rows, err := q.db.QueryContext(ctx, getBookingItems, bookingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BookingItem
	for rows.Next() {
		var i BookingItem
		if err := rows.Scan(
			&i.BookingItemID,
			&i.BookingID,
			&i.ServiceID,
			&i.Quantity,
			&i.UnitPriceCents,
			&i.PointsAward,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
