// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: job.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createJob = `-- name: CreateJob :one
INSERT INTO job (booking_id, assigned_to_user_id)
VALUES (
    $1,
    $2
) RETURNING job_id, booking_id, assigned_to_user_id, status, started_at, completed_at, delivered_at, created_at, updated_at
`

type CreateJobParams struct {
	BookingID        uuid.UUID
	AssignedToUserID uuid.NullUUID
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, createJob, arg.BookingID, arg.AssignedToUserID)
	var i Job
	err := row.Scan(
		&i.JobID,
		&i.BookingID,
		&i.AssignedToUserID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
