// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: job.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createJob = `-- name: CreateJob :one
INSERT INTO job (booking_id, assigned_to_user_id, dropbox_folder_path)
VALUES (
    $1,
    $2,
    $3
) RETURNING job_id, booking_id, assigned_to_user_id, status, started_at, completed_at, delivered_at, created_at, updated_at, google_event_id, dropbox_folder_path
`

type CreateJobParams struct {
	BookingID         uuid.UUID
	AssignedToUserID  uuid.NullUUID
	DropboxFolderPath sql.NullString
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, createJob, arg.BookingID, arg.AssignedToUserID, arg.DropboxFolderPath)
	var i Job
	err := row.Scan(
		&i.JobID,
		&i.BookingID,
		&i.AssignedToUserID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GoogleEventID,
		&i.DropboxFolderPath,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT job_id, booking_id, assigned_to_user_id, status, started_at, completed_at, delivered_at, created_at, updated_at, google_event_id, dropbox_folder_path FROM job WHERE job_id = $1
`

func (q *Queries) GetJob(ctx context.Context, jobID uuid.UUID) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJob, jobID)
	var i Job
	err := row.Scan(
		&i.JobID,
		&i.BookingID,
		&i.AssignedToUserID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GoogleEventID,
		&i.DropboxFolderPath,
	)
	return i, err
}

const insertEventID = `-- name: InsertEventID :one
UPDATE job
SET google_event_id = $2
WHERE job_id = $1
RETURNING job_id, booking_id, assigned_to_user_id, status, started_at, completed_at, delivered_at, created_at, updated_at, google_event_id, dropbox_folder_path
`

type InsertEventIDParams struct {
	JobID         uuid.UUID
	GoogleEventID sql.NullString
}

func (q *Queries) InsertEventID(ctx context.Context, arg InsertEventIDParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, insertEventID, arg.JobID, arg.GoogleEventID)
	var i Job
	err := row.Scan(
		&i.JobID,
		&i.BookingID,
		&i.AssignedToUserID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GoogleEventID,
		&i.DropboxFolderPath,
	)
	return i, err
}
