// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: job_asset.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createJobAsset = `-- name: CreateJobAsset :one
INSERT INTO job_asset (
job_id,
created_by_user_id,
asset_type,
dropbox_path,
dropbox_file_id,
file_name,
mime_type,
size_bytes,
checksum_sha256,
is_primary,
sort_order
)
VALUES (
$1,
$2,
$3,
$4,
$5,
$6,
$7,
$8,
$9,
$10,
$11
)
RETURNING asset_id, job_id, created_by_user_id, asset_type, dropbox_path, dropbox_file_id, file_name, mime_type, size_bytes, checksum_sha256, is_primary, sort_order, created_at
`

type CreateJobAssetParams struct {
	JobID           uuid.UUID
	CreatedByUserID uuid.NullUUID
	AssetType       string
	DropboxPath     string
	DropboxFileID   sql.NullString
	FileName        string
	MimeType        string
	SizeBytes       int64
	ChecksumSha256  sql.NullString
	IsPrimary       bool
	SortOrder       int32
}

func (q *Queries) CreateJobAsset(ctx context.Context, arg CreateJobAssetParams) (JobAsset, error) {
	row := q.db.QueryRowContext(ctx, createJobAsset,
		arg.JobID,
		arg.CreatedByUserID,
		arg.AssetType,
		arg.DropboxPath,
		arg.DropboxFileID,
		arg.FileName,
		arg.MimeType,
		arg.SizeBytes,
		arg.ChecksumSha256,
		arg.IsPrimary,
		arg.SortOrder,
	)
	var i JobAsset
	err := row.Scan(
		&i.AssetID,
		&i.JobID,
		&i.CreatedByUserID,
		&i.AssetType,
		&i.DropboxPath,
		&i.DropboxFileID,
		&i.FileName,
		&i.MimeType,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.IsPrimary,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}
