// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type AuthIdentity struct {
	IdentityID      uuid.UUID
	UserID          uuid.UUID
	Provider        string
	ProviderSubject sql.NullString
	ProviderHash    sql.NullString
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type OrgMembership struct {
	MembershipID   uuid.UUID
	OrganizationID uuid.UUID
	UserID         uuid.UUID
	OrgRole        string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Organization struct {
	OrganizationID   uuid.UUID
	Name             string
	OrganizationType string
	Status           string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type Service struct {
	ServiceID         uuid.UUID
	Name              string
	Code              string
	Description       sql.NullString
	BasePrice         string
	BasePointsRewards int32
	IsActive          bool
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type User struct {
	UserID      uuid.UUID
	Email       string
	FirstName   string
	LastName    string
	Phone       sql.NullString
	IsAdmin     bool
	Status      string
	LastLoginAt sql.NullTime
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
