// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type User struct {
	UserID      uuid.UUID
	Email       string
	FirstName   string
	LastName    string
	Phone       sql.NullString
	IsAdmin     bool
	Status      string
	LastLoginAt sql.NullTime
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
