// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: oauth.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createOauthConnection = `-- name: CreateOauthConnection :one
INSERT INTO user_oauth_connections (user_id,
    provider,
    service, 
    provider_email, 
    refresh_token, 
    access_token, 
    expires_at, 
    scopes)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
) RETURNING connection_id, user_id, provider, service, provider_email, refresh_token, access_token, expires_at, scopes, created_at, updated_at
`

type CreateOauthConnectionParams struct {
	UserID        uuid.UUID
	Provider      string
	Service       string
	ProviderEmail sql.NullString
	RefreshToken  string
	AccessToken   sql.NullString
	ExpiresAt     sql.NullTime
	Scopes        sql.NullString
}

func (q *Queries) CreateOauthConnection(ctx context.Context, arg CreateOauthConnectionParams) (UserOauthConnection, error) {
	row := q.db.QueryRowContext(ctx, createOauthConnection,
		arg.UserID,
		arg.Provider,
		arg.Service,
		arg.ProviderEmail,
		arg.RefreshToken,
		arg.AccessToken,
		arg.ExpiresAt,
		arg.Scopes,
	)
	var i UserOauthConnection
	err := row.Scan(
		&i.ConnectionID,
		&i.UserID,
		&i.Provider,
		&i.Service,
		&i.ProviderEmail,
		&i.RefreshToken,
		&i.AccessToken,
		&i.ExpiresAt,
		&i.Scopes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
