// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: org_membership.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createOrgMembership = `-- name: CreateOrgMembership :one
INSERT INTO org_membership (organization_id, user_id, org_role)
VALUES(
    $1,
    $2,
    $3
)
RETURNING membership_id, organization_id, user_id, org_role, created_at, updated_at
`

type CreateOrgMembershipParams struct {
	OrganizationID uuid.UUID
	UserID         uuid.UUID
	OrgRole        string
}

func (q *Queries) CreateOrgMembership(ctx context.Context, arg CreateOrgMembershipParams) (OrgMembership, error) {
	row := q.db.QueryRowContext(ctx, createOrgMembership, arg.OrganizationID, arg.UserID, arg.OrgRole)
	var i OrgMembership
	err := row.Scan(
		&i.MembershipID,
		&i.OrganizationID,
		&i.UserID,
		&i.OrgRole,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
