// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: organization.sql

package database

import (
	"context"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organization (name, organization_type)
VALUES (
    $1,
    $2
) RETURNING organization_id, name, organization_type, status, created_at, updated_at
`

type CreateOrganizationParams struct {
	Name             string
	OrganizationType string
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRowContext(ctx, createOrganization, arg.Name, arg.OrganizationType)
	var i Organization
	err := row.Scan(
		&i.OrganizationID,
		&i.Name,
		&i.OrganizationType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
