// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: point_ledger.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createPointLedger = `-- name: CreatePointLedger :one
INSERT INTO point_ledger (organization_id, user_id, event_type, event_id, points_delta, description)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
) RETURNING ledger_id, organization_id, user_id, event_type, event_id, points_delta, description, created_at
`

type CreatePointLedgerParams struct {
	OrganizationID uuid.UUID
	UserID         uuid.NullUUID
	EventType      string
	EventID        uuid.NullUUID
	PointsDelta    int32
	Description    sql.NullString
}

func (q *Queries) CreatePointLedger(ctx context.Context, arg CreatePointLedgerParams) (PointLedger, error) {
	row := q.db.QueryRowContext(ctx, createPointLedger,
		arg.OrganizationID,
		arg.UserID,
		arg.EventType,
		arg.EventID,
		arg.PointsDelta,
		arg.Description,
	)
	var i PointLedger
	err := row.Scan(
		&i.LedgerID,
		&i.OrganizationID,
		&i.UserID,
		&i.EventType,
		&i.EventID,
		&i.PointsDelta,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}
