// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: property.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createProperty = `-- name: CreateProperty :one
INSERT INTO property(organization_id, created_by_user_id, address_line1, address_line2, city, state_region, postal_code, listing_url)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
) RETURNING property_id, organization_id, created_by_user_id, address_line1, address_line2, city, state_region, postal_code, listing_url, created_at, updated_at
`

type CreatePropertyParams struct {
	OrganizationID  uuid.UUID
	CreatedByUserID uuid.NullUUID
	AddressLine1    string
	AddressLine2    sql.NullString
	City            string
	StateRegion     string
	PostalCode      string
	ListingUrl      sql.NullString
}

func (q *Queries) CreateProperty(ctx context.Context, arg CreatePropertyParams) (Property, error) {
	row := q.db.QueryRowContext(ctx, createProperty,
		arg.OrganizationID,
		arg.CreatedByUserID,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.City,
		arg.StateRegion,
		arg.PostalCode,
		arg.ListingUrl,
	)
	var i Property
	err := row.Scan(
		&i.PropertyID,
		&i.OrganizationID,
		&i.CreatedByUserID,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.StateRegion,
		&i.PostalCode,
		&i.ListingUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
