// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: redemption.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const approveRedemption = `-- name: ApproveRedemption :one
UPDATE redemption
SET
    status = 'approved',
    approved_at = NOW()
WHERE redemption_id = $1
RETURNING redemption_id, organization_id, requested_by_user_id, reward_id, applied_booking_id, status, points_cost, created_at, approved_at, cancelled_at
`

func (q *Queries) ApproveRedemption(ctx context.Context, redemptionID uuid.UUID) (Redemption, error) {
	row := q.db.QueryRowContext(ctx, approveRedemption, redemptionID)
	var i Redemption
	err := row.Scan(
		&i.RedemptionID,
		&i.OrganizationID,
		&i.RequestedByUserID,
		&i.RewardID,
		&i.AppliedBookingID,
		&i.Status,
		&i.PointsCost,
		&i.CreatedAt,
		&i.ApprovedAt,
		&i.CancelledAt,
	)
	return i, err
}

const createRedemption = `-- name: CreateRedemption :one
INSERT INTO redemption (
organization_id,
requested_by_user_id,
reward_id,
applied_booking_id,
points_cost,
status
)
VALUES (
$1,
$2,
$3,
$4,
$5,
'pending'
)
RETURNING redemption_id, organization_id, requested_by_user_id, reward_id, applied_booking_id, status, points_cost, created_at, approved_at, cancelled_at
`

type CreateRedemptionParams struct {
	OrganizationID    uuid.UUID
	RequestedByUserID uuid.UUID
	RewardID          uuid.UUID
	AppliedBookingID  uuid.UUID
	PointsCost        int32
}

func (q *Queries) CreateRedemption(ctx context.Context, arg CreateRedemptionParams) (Redemption, error) {
	row := q.db.QueryRowContext(ctx, createRedemption,
		arg.OrganizationID,
		arg.RequestedByUserID,
		arg.RewardID,
		arg.AppliedBookingID,
		arg.PointsCost,
	)
	var i Redemption
	err := row.Scan(
		&i.RedemptionID,
		&i.OrganizationID,
		&i.RequestedByUserID,
		&i.RewardID,
		&i.AppliedBookingID,
		&i.Status,
		&i.PointsCost,
		&i.CreatedAt,
		&i.ApprovedAt,
		&i.CancelledAt,
	)
	return i, err
}

const getRedemptionFromID = `-- name: GetRedemptionFromID :one
SELECT redemption_id, organization_id, requested_by_user_id, reward_id, applied_booking_id, status, points_cost, created_at, approved_at, cancelled_at FROM redemption WHERE redemption_id = $1
`

func (q *Queries) GetRedemptionFromID(ctx context.Context, redemptionID uuid.UUID) (Redemption, error) {
	row := q.db.QueryRowContext(ctx, getRedemptionFromID, redemptionID)
	var i Redemption
	err := row.Scan(
		&i.RedemptionID,
		&i.OrganizationID,
		&i.RequestedByUserID,
		&i.RewardID,
		&i.AppliedBookingID,
		&i.Status,
		&i.PointsCost,
		&i.CreatedAt,
		&i.ApprovedAt,
		&i.CancelledAt,
	)
	return i, err
}
