// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: reward.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createReward = `-- name: CreateReward :one
INSERT INTO reward(code, name, description, service_id, points_cost)
VALUES(
    $1,
    $2,
    $3,
    $4,
    $5
) RETURNING reward_id, code, name, description, service_id, points_cost, is_active, created_at, updated_at
`

type CreateRewardParams struct {
	Code        string
	Name        string
	Description sql.NullString
	ServiceID   uuid.UUID
	PointsCost  int32
}

func (q *Queries) CreateReward(ctx context.Context, arg CreateRewardParams) (Reward, error) {
	row := q.db.QueryRowContext(ctx, createReward,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.ServiceID,
		arg.PointsCost,
	)
	var i Reward
	err := row.Scan(
		&i.RewardID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.ServiceID,
		&i.PointsCost,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRewardFromID = `-- name: GetRewardFromID :one
SELECT reward_id, code, name, description, service_id, points_cost, is_active, created_at, updated_at FROM reward WHERE reward_id = $1
`

func (q *Queries) GetRewardFromID(ctx context.Context, rewardID uuid.UUID) (Reward, error) {
	row := q.db.QueryRowContext(ctx, getRewardFromID, rewardID)
	var i Reward
	err := row.Scan(
		&i.RewardID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.ServiceID,
		&i.PointsCost,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRewardFromServiceID = `-- name: GetRewardFromServiceID :one
SELECT reward_id, code, name, description, service_id, points_cost, is_active, created_at, updated_at FROM reward WHERE service_id = $1
`

func (q *Queries) GetRewardFromServiceID(ctx context.Context, serviceID uuid.UUID) (Reward, error) {
	row := q.db.QueryRowContext(ctx, getRewardFromServiceID, serviceID)
	var i Reward
	err := row.Scan(
		&i.RewardID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.ServiceID,
		&i.PointsCost,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
