// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: state.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createOAuthState = `-- name: CreateOAuthState :one
INSERT INTO oauth_states(state, user_id, expires_at)
VALUES(
    $1,
    $2,
    $3
)RETURNING state, user_id, created_at, expires_at
`

type CreateOAuthStateParams struct {
	State     string
	UserID    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) CreateOAuthState(ctx context.Context, arg CreateOAuthStateParams) (OauthState, error) {
	row := q.db.QueryRowContext(ctx, createOAuthState, arg.State, arg.UserID, arg.ExpiresAt)
	var i OauthState
	err := row.Scan(
		&i.State,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getUserFromState = `-- name: GetUserFromState :one
SELECT state, user_id, created_at, expires_at FROM oauth_states WHERE state = $1
`

func (q *Queries) GetUserFromState(ctx context.Context, state string) (OauthState, error) {
	row := q.db.QueryRowContext(ctx, getUserFromState, state)
	var i OauthState
	err := row.Scan(
		&i.State,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
